# KirosUtilities plugin config - 1.1
# Mensajes
messages:
  reload_success: "&eLa configuración de &dKirosUtilities &ese ha recargado con &aéxito&e."
  no_permission: "&cNo tienes permisos para ejecutar ese comando."

# Bloques que los pistones ya no van a poder empujar, se tienen que añadir en mayus todos.
# También se puede añadir "*" para evitar que los pistones empujen cualquier tipo de bloque (Incluso aire).
blocked_blocks:
#  - "*"
  - PISTON
  - STICKY_PISTON


# TabCompletionFilter - Si el "enabled" se pone en "false" esta sección no hará nada.
# Si está activo, todos los comandos desaparecerán de la lista de comandos sugeridos y no se autocompletarán al pulsar TAB.
# Exceptuando los comandos que estén en la whitelist.
# Al añadir un comando todos los subcomandos de ese comando se añaden automáticamente.
# Este filtro no afecta a los jugadores con OP o que tengan el permiso kirosutilities.tabcompletionfilter.exempt
TabCompletionFilter:
  enabled: true

# Esta whitelist afectará a todos los jugadores a no ser que tengan OP, el permiso exempt o el permiso de una whitelist custom
# donde "include_default" esté en "false".
  default_whitelist:
    - "spawn"
    - "msg"
    - "tell"
    - "warp"
    - "tpa"
    - "tpaccept"


# Aquí se pueden añadir permisos custom para ampliar o limitar más la whitelist para algunos jugadores.
# Si "include_default" está en "true" los jugadores con este permiso se verán afectados por la whitelist default + la whitelist custom en concreto.
# Si está en "false" solo se verán afectados por la whitelist custom.
# Se pueden eliminar todas las whitelists cutom, dejando este apartado así "custom_whitelists: []"
# También se pueden añadir tantas whitelists custom como se deseen.
  custom_whitelists:

    - permission: "kirosutilities.custom.staff"
      commands:
        - "ban"
        - "kick"
        - "warn"
        - "mute"
        - "tempban"
        - "tempwarn"
        - "tempmute"
        - "unwarn"
        - "history"
        - "dupeip"
        - "find"
        - "server"
        - "unban"
        - "unmute"
        - "warnings"
      
      include_default: true
   
# Fin de la config.